version: '3.4'

services:

  padraoapi:
    container_name: padraopi2
    image: xexel7/apipadrao2:latest
    #build:
      #context: .
     # dockerfile: Dockerfile
    networks:
      - jof-network
    ports:
      - 8000:5000
    volumes:
      - ./db:/app/db

networks:
  jof-network:
    driver: bridge

